version: "3.9"

services:
  # ===== Storages =====

  db:
    image: postgres
    container_name: ps_db
    restart: always
    environment:
      POSTGRES_DB: "ps_db"
      POSTGRES_USER: "moderator"
      POSTGRES_PASSWORD: "2222"
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - ./scripts/migrations/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./scripts/migrations/fill_db.sql:/docker-entrypoint-initdb.d/2.sql
    networks:
      - ps-network
    deploy:
      restart_policy:
        condition: on-failure

  redis:
    image: redis:alpine3.18
    container_name: ps_redis
    restart: always
    environment:
      REDIS_PASSWORD: "1234"
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    networks:
      - ps-network
    deploy:
      restart_policy:
        condition: on-failure

  # ===== Services =====

  api:
    image: ps_api
    build:
      context: .
      dockerfile: ./cmd/api/Dockerfile
    container_name: ps_api
    depends_on:
      - db
      - redis
    volumes:
      - ./cmd/api/logs:/logs
      - ./configs/api_main.yaml:/configs/api.yaml
      - ./.aws:/root/.aws
    networks:
      - ps-network
    deploy:
      restart_policy:
        condition: on-failure

  ml:
    image: vazhid/ml_serve:0.0.2
    container_name: ps_ml
    networks:
      - ps-network
    deploy:
      restart_policy:
        condition: on-failure

  nginx:
    image: ps_nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: ps_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
#      - ./certbot/conf:/etc/letsencrypt
#      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    networks:
      - ps-network
    deploy:
      restart_policy:
        condition: on-failure

#  certbot:
#    image: certbot/certbot
#    container_name: ps_certbot
#    volumes:
#      - ./certbot/conf:/etc/letsencrypt
#      - ./certbot/www:/var/www/certbot
#    command: certonly --webroot --webroot-path /var/www/certbot --force-renewal --email=slav.shagal@yandex.ru -d prospeech.tech \
#      --agree-tos --no-eff-email

networks:
  ps-network:
    name: ps_network
    driver: bridge
