name: CI/CD

on: push

jobs:
#  lint:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out repository code
#        uses: actions/checkout@v4.1.1
#
#      - name: Run lint
#        run: make lint

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4.1.1

      - name: Run build
        run: make build

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Install SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} > ~/.ssh/known_hosts

      - name: Connect and Deploy
        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "cd ${{ secrets.SERVER_WORKDIR }} && make deploy"

      - name: Clean
        run: rm -rf ~/.ssh
